name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  MACOSX_DEPLOYMENT_TARGET: 12.0

jobs:
  Build:
    name: Conda-Forge LPython Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019", "macos-latest", "ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: ${{ github.job }}-${{ matrix.os }}

      - name: Clone LPython Source Repository
        shell: bash -e -l {0}
        run: |
            git clone https://github.com/lcompilers/lpython.git
            git fetch https://github.com/lcompilers/lpython.git --tags -f
            git checkout v0.20.0

      - name: Run LPython Integration Tests
        if: ${{ !startsWith(matrix.os, 'windows-2019') }}
        shell: bash -e -l {0}
        run: |
            cd lpython/integration_tests
            ./run_tests.py -b llvm c wasm

      - name: Run LPython Fast Integration Tests
        if: ${{ !startsWith(matrix.os, 'windows-2019') }}
        shell: bash -e -l {0}
        run: |
            cd lpython/integration_tests
            ./run_tests.py -b llvm c wasm -f

      - name: Run LPython Reference Tests
        if: ${{ !startsWith(matrix.os, 'windows-2019') }}
        shell: bash -e -l {0}
        run: |
            cd lpython
            ./run_tests.py --skip-run-with-dbg
